export enum SAGA_ACTIONS {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  GET_EXPENDITURES = "GET_EXPENDITURES",
  GET_PLAYERS = "GET_PLAYERS",
  ADD_PLAYER = "ADD_PLAYER",
  DELETE_PLAYER = "DELETE_PLAYER",
}
